/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/telemetry/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telemetry Data */
        get: operations["get_telemetry_data_api_v1_telemetry_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/prewarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prewarm
         * @description Warm the FastF1 session cache for (year, gp, session) in the background.
         *
         *     The frontend calls this when the user picks a session, so the ~2-15s parse
         *     starts while they choose drivers — by the time lap-times/telemetry fire, the
         *     session is already loaded and the charts fall in instead of hanging.
         *     Returns 202 immediately; the load runs after the response is sent.
         */
        post: operations["prewarm_api_v1_telemetry_prewarm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/gps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gps
         * @description Get available Grand Prix events for a specific year.
         */
        get: operations["get_gps_api_v1_telemetry_gps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sessions
         * @description Get available sessions for a specific Grand Prix.
         */
        get: operations["get_sessions_api_v1_telemetry_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Drivers
         * @description Get available drivers for a specific session.
         */
        get: operations["get_drivers_api_v1_telemetry_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/lap-times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lap-time series for one or more drivers (pace comparison chart)
         * @description Use this tool when the user wants a CHART of lap times across a stint or race — pace evolution, who was faster lap-by-lap, tyre-life effects on lap time.  Accepts one driver (single trace) or several comma-separated codes (overlay).  Returns the full lap-time list per driver; the frontend renders a Plotly line chart inline.  Prefer this over predict_pace for historical pace comparison; use predict_pace only when the user asks to FORECAST a future race lap.
         */
        get: operations["get_lap_times"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/lap-telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Speed / throttle / brake trace for ONE driver on ONE lap
         * @description Use this tool when the user wants the telemetry of a SPECIFIC lap for a single driver — speed graph, throttle / brake / RPM trace, gear shifts, DRS activations.  Requires a concrete lap number (1-80).  Lap 1 typically has no data (formation lap) — do not default to 1; either pick a sensible mid-race lap or ask the user.  For comparing telemetry of two drivers use compare_drivers instead.
         */
        get: operations["get_telemetry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/race-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full race overview — positions and lap times for a Grand Prix
         * @description Use this tool when the user wants a HIGH-LEVEL view of a race (position evolution lap-by-lap, multi-driver pace overview, stint-by-stint chart) rather than a single driver's telemetry or a head-to-head comparison.  Reads the pre-built featured parquet so it's fast and covers the whole field by default; pass driver codes to restrict.  Frontend renders position + lap-time subplots.
         */
        get: operations["get_race_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circuit-domination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Circuit Domination
         * @description Get circuit domination visualization data.
         *
         *     Returns GPS coordinates and colors for each microsector based on
         *     which driver was fastest in that section of the track.
         *
         *     **Parameters:**
         *     - **year**: Racing season year (2018-2030)
         *     - **gp**: Grand Prix name (must match FastF1 naming)
         *     - **session**: Session type (FP1, FP2, FP3, Q, R, S, SQ)
         *     - **drivers**: Comma-separated driver codes (max 3)
         *
         *     **Returns:**
         *     ```json
         *     {
         *         "x": [100.5, 101.2, ...],
         *         "y": [50.3, 51.1, ...],
         *         "colors": ["#A259F7", "#00B4D8", ...],
         *         "drivers": [
         *             {"driver": "VER", "color": "#A259F7"},
         *             {"driver": "NOR", "color": "#00B4D8"}
         *         ]
         *     }
         *     ```
         *
         *     **Example:**
         *     ```
         *     GET /api/v1/circuit-domination?year=2024&gp=Spain&session=Q&drivers=VER,LEC
         *     ```
         */
        get: operations["get_circuit_domination_api_v1_circuit_domination_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparison/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare two drivers' fastest-lap telemetry head-to-head
         * @description Use this tool whenever the user asks to compare two drivers, their fastest laps, qualifying laps, race pace head-to-head, speed traces, throttle, brake or microsector dominance.  Returns synchronised telemetry overlay plus a delta-time series the frontend renders as an inline chart.  Picks the fastest lap of each driver in the requested session automatically — the caller does NOT need to know specific lap numbers.  Prefer this over predict_pace whenever the user asks for telemetry comparison (predict_pace is for race lap-time forecasting, not historical qualifying telemetry).
         */
        get: operations["compare_drivers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if LM Studio is accessible and healthy.
         *
         *     Returns:
         *         Health status information
         */
        get: operations["health_check_api_v1_chat_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Get list of available models from LM Studio.
         *
         *     Returns:
         *         List of model names
         */
        get: operations["get_models_api_v1_chat_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Chat Message
         * @description Send a message to LM Studio and get the complete response (non-streaming).
         *
         *     Args:
         *         request: Chat request with message, history, and parameters
         *
         *     Returns:
         *         Complete chat response
         */
        post: operations["send_chat_message_api_v1_chat_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Chat Message
         * @description Send a message to LM Studio and stream the response.
         *
         *     Args:
         *         request: Chat request with message, history, and parameters
         *
         *     Returns:
         *         Streaming response with text chunks
         */
        post: operations["stream_chat_message_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chat Status
         * @description Return the latest backend stage for *request_id* (smart-spinner poll target).
         *
         *     The Streamlit chat polls this endpoint every ~1s while a message is in
         *     flight so the spinner label can mirror the real backend stage instead
         *     of rotating fake placeholders.
         */
        get: operations["chat_status_api_v1_chat_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/tool-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tool Message
         * @description Tool-aware chat — non-streaming JSON variant.
         *
         *     Drives ``chat_engine.get_response`` and packages the result into the
         *     ``ToolMessageResponse`` shape the rest of the API expects.  The
         *     optional ``X-Request-Id`` header is echoed into the stage tracker so
         *     the frontend's smart-spinner poll target (``/chat/status``) keeps
         *     working even for non-streaming consumers.
         */
        post: operations["tool_message_api_v1_chat_tool_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/tool-message-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tool Message Stream
         * @description Tool-aware chat — Server-Sent Events streaming variant.
         *
         *     Yields the same event sequence the frontend has consumed since v1.3:
         *     ``stage`` (whenever the backend phase advances), ``tool_result`` (rich
         *     structured payload that maps to the chat's tool renderers), ``token``
         *     (LLM text chunks for the live-typing UX), and ``done`` (final marker
         *     with provider metadata).  All formatting concerns live in this module;
         *     the ``chat_engine`` only produces (event, payload) tuples.
         */
        post: operations["tool_message_stream_api_v1_chat_tool_message_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/available-gps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available Gps
         * @description Return the list of GP names available in the featured parquet.
         */
        get: operations["available_gps_api_v1_strategy_available_gps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/available-drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available Drivers
         * @description Return driver codes for a specific GP in the featured parquet.
         */
        get: operations["available_drivers_api_v1_strategy_available_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/lap-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lap Range
         * @description Return the min/max lap numbers for a driver in a GP.
         */
        get: operations["lap_range_api_v1_strategy_lap_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/lap-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lap State
         * @description Build the canonical lap_state dict for one (gp, driver, lap).
         *
         *     Reads the featured parquet first; when that lap was dropped from it
         *     (Safety Car / pit / out lap), falls back to the raw per-race parquet so any
         *     lap is runnable, exactly like the arcade replay. The returned structure
         *     matches RaceStateManager.get_lap_state() either way, so it can be passed
         *     directly to any agent endpoint.
         */
        get: operations["get_lap_state_api_v1_strategy_lap_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/pace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Pace
         * @description Run the Pace Agent (N25) for a single lap.
         */
        post: operations["predict_pace_api_v1_strategy_pace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/pace-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Pace Range
         * @description Run Pace Agent across a lap range and return actual vs predicted.
         */
        post: operations["predict_pace_range_api_v1_strategy_pace_range_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/tire-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Tire Range
         * @description Run the TireDegTCN across a lap range for the Tyres agent-tab chart.
         *
         *     Returns, per lap in the window, the ACTUAL cumulative fuel-adjusted degradation
         *     (the parquet's `FuelAdjustedDegAbsolute`, i.e. the TCN's own training target)
         *     and the model's PREDICTED value (a deterministic forward pass over the stint up
         *     to that lap). Laps the featured parquet dropped (Safety Car / out laps) are
         *     simply absent from the series, so the lines break there rather than erroring.
         *
         *     The tire agent is set up once (its `laps_df`/`session_meta`), then only the
         *     cheap deterministic predict path runs per lap — no per-lap MC Dropout.
         */
        post: operations["predict_tire_range_api_v1_strategy_tire_range_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/tire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Tire
         * @description Run the Tire Agent (N26) for a single lap.
         */
        post: operations["predict_tire_api_v1_strategy_tire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/situation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Situation
         * @description Run the Race Situation Agent (N27) for a single lap.
         */
        post: operations["predict_situation_api_v1_strategy_situation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/pit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict Pit
         * @description Run the Pit Strategy Agent (N28) for a single lap.
         */
        post: operations["predict_pit_api_v1_strategy_pit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/radio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Radio
         * @description Run the Radio Agent (N29) for a single lap.
         */
        post: operations["analyze_radio_api_v1_strategy_radio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/rag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Rag
         * @description Run the RAG Agent (N30) to answer a regulation question.
         */
        post: operations["query_rag_api_v1_strategy_rag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend Strategy
         * @description Run the full Strategy Orchestrator (N31) for a single lap.
         */
        post: operations["recommend_strategy_api_v1_strategy_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/radio-available-gps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radio Available Gps
         * @description Return GP names that have a radio corpus for the given year.
         */
        get: operations["radio_available_gps_api_v1_strategy_radio_available_gps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/radio-laps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radio Laps
         * @description Return drivers and their laps that have radio messages.
         *
         *     If *driver* is provided (3-letter code, e.g. 'VER'), only that driver's
         *     laps are returned.  Otherwise all drivers with radio are listed.
         */
        get: operations["radio_laps_api_v1_strategy_radio_laps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/radio-transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radio Transcript
         * @description Return the transcript text for a specific driver/lap radio message.
         */
        get: operations["radio_transcript_api_v1_strategy_radio_transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Stream per-lap strategy decisions as Server-Sent Events.
         *
         *     Each event is a JSON blob in the ``data: ...\n\n`` SSE frame format. The
         *     stream begins with a single ``start`` event, then emits one ``lap`` (or
         *     ``error``) event per processed lap, and closes with a ``summary``. A
         *     heartbeat comment is sent every 15 lap events so long runs survive proxy
         *     idle timeouts.
         */
        post: operations["simulate_api_v1_strategy_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Unauthenticated liveness probe (open path — see core/auth.py OPEN_PATHS).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description Request model for chat messages.
         */
        ChatRequest: {
            /** Text */
            text: string;
            /** Image */
            image?: string | null;
            /** Chat History */
            chat_history?: {
                [key: string]: unknown;
            }[] | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
            /** Model */
            model?: string | null;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Max Tokens
             * @default 1000
             */
            max_tokens: number;
        };
        /**
         * ChatResponse
         * @description Response model for chat messages.
         */
        ChatResponse: {
            /** Response */
            response: string;
            /** Llm Model */
            llm_model?: string | null;
            /** Tokens Used */
            tokens_used?: number | null;
        };
        /**
         * DisplayType
         * @description How the frontend should render a tool result inside a chat bubble.
         * @enum {string}
         */
        DisplayType: "metrics" | "strategy_card" | "table" | "chart" | "text";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for health check.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Lm Studio Reachable */
            lm_studio_reachable: boolean;
            /** Message */
            message: string;
            /** Models Available */
            models_available?: number | null;
        };
        /**
         * PaceRangeRequest
         * @description Batch pace predictions across a lap range.
         */
        PaceRangeRequest: {
            /**
             * Year
             * @default 2025
             */
            year: number;
            /** Gp */
            gp: string;
            /** Driver */
            driver: string;
            /** Lap Start */
            lap_start: number;
            /** Lap End */
            lap_end: number;
        };
        /**
         * PaceRequest
         * @description Request body for the /pace endpoint (N25 XGBoost lap-time prediction).
         */
        PaceRequest: {
            /** Lap State */
            lap_state: {
                [key: string]: unknown;
            };
        };
        /**
         * PitRequest
         * @description Request body for the /pit endpoint (N28 stop duration + N16 undercut).
         */
        PitRequest: {
            /** Lap State */
            lap_state: {
                [key: string]: unknown;
            };
        };
        /**
         * RadioRequest
         * @description Request body for the /radio endpoint (N29 NLP pipeline + RCM parser).
         *
         *     radio_msgs and rcm_events must be lists of plain dicts matching the
         *     RadioMessage / RCMEvent field names respectively.
         */
        RadioRequest: {
            /** Lap State */
            lap_state: {
                [key: string]: unknown;
            };
            /** Radio Msgs */
            radio_msgs?: {
                [key: string]: unknown;
            }[];
            /** Rcm Events */
            rcm_events?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * RagRequest
         * @description Request body for the /rag regulation-lookup endpoint.
         */
        RagRequest: {
            /** Question */
            question: string;
        };
        /**
         * RecommendRequest
         * @description Request body for the full orchestrator endpoint (/recommend).
         *
         *     Accepts the raw lap_state dict produced by RaceStateManager.  The
         *     endpoint derives RaceState from it internally so the caller does not
         *     need to know the RaceState schema.
         */
        RecommendRequest: {
            /** Lap State */
            lap_state: {
                [key: string]: unknown;
            };
            /**
             * Gp Name
             * @default
             */
            gp_name: string;
            /**
             * Year
             * @default 2025
             */
            year: number;
            /**
             * Gap Ahead S
             * @default 2
             */
            gap_ahead_s: number;
            /**
             * Pace Delta S
             * @default 0
             */
            pace_delta_s: number;
            /**
             * Risk Tolerance
             * @default 0.5
             */
            risk_tolerance: number;
            /** Radio Msgs */
            radio_msgs?: {
                [key: string]: unknown;
            }[] | null;
            /** Rcm Events */
            rcm_events?: {
                [key: string]: unknown;
            }[] | null;
            /** Rival */
            rival?: string | null;
        };
        /**
         * SimulateRequest
         * @description Inputs for a streamed race simulation run.
         *
         *     Mirrors the ``SimConfig`` dataclass in the simulation service; we keep a
         *     Pydantic equivalent here so FastAPI can validate and document the payload
         *     without importing the service module at schema-generation time.
         */
        SimulateRequest: {
            /**
             * Year
             * @default 2025
             */
            year: number;
            /** Gp */
            gp: string;
            /** Driver */
            driver: string;
            /** Team */
            team: string;
            /** Driver2 */
            driver2?: string | null;
            /** Lap Range */
            lap_range?: [
                number,
                number
            ] | null;
            /**
             * Risk Tolerance
             * @default 0.5
             */
            risk_tolerance: number;
            /**
             * No Llm
             * @default false
             */
            no_llm: boolean;
            /**
             * Provider
             * @default lmstudio
             */
            provider: string;
            /**
             * Interval S
             * @default 0
             */
            interval_s: number;
        };
        /**
         * SituationRequest
         * @description Request body for the /situation endpoint (N27 overtake + SC probability).
         */
        SituationRequest: {
            /** Lap State */
            lap_state: {
                [key: string]: unknown;
            };
        };
        /**
         * StrategyResponse
         * @description Generic envelope returned by every strategy endpoint.
         */
        StrategyResponse: {
            /** Agent */
            agent: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /**
         * TireRequest
         * @description Request body for the /tire endpoint (N26 TireDegTCN cliff estimation).
         */
        TireRequest: {
            /** Lap State */
            lap_state: {
                [key: string]: unknown;
            };
        };
        /**
         * ToolMessageRequest
         * @description Request body for POST /api/v1/chat/tool-message.
         *
         *     Identical to ChatRequest but explicitly typed so FastAPI generates
         *     a separate OpenAPI schema (easier to version independently).
         */
        ToolMessageRequest: {
            /**
             * Text
             * @description User message.
             */
            text: string;
            /**
             * Image
             * @description Base64-encoded image for multimodal models.
             */
            image?: string | null;
            /**
             * Chat History
             * @description Prior messages for context.
             */
            chat_history?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Context
             * @description Arbitrary context (e.g. current GP/driver).
             */
            context?: {
                [key: string]: unknown;
            } | null;
            /**
             * Model
             * @description Override LM Studio model.
             */
            model?: string | null;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Max Tokens
             * @default 1000
             */
            max_tokens: number;
            /**
             * Stream Tokens
             * @description Stream the tool-summary reply as live token deltas instead of one full-text event. Only changes the second LLM call (the summary of a dispatched tool's result) — the first call, which decides whether to call a tool at all, always stays non-streaming. Default False keeps today's single-token behaviour for callers that never send this flag.
             * @default false
             */
            stream_tokens: boolean;
        };
        /**
         * ToolMessageResponse
         * @description Response for the tool-aware chat endpoint.
         *
         *     Always contains a human-readable *response*.  When a tool was invoked
         *     successfully, *tool_result* carries the structured data for rich rendering.
         */
        ToolMessageResponse: {
            /**
             * Response
             * @description Natural-language assistant reply.
             */
            response: string;
            /** Llm Model */
            llm_model?: string | null;
            /** Tokens Used */
            tokens_used?: number | null;
            /** @description Present only when a strategy tool was invoked and returned data. */
            tool_result?: components["schemas"]["ToolResultData"] | null;
        };
        /**
         * ToolResultData
         * @description Structured output attached to a chat response when a tool was invoked.
         *
         *     The frontend inspects *display_type* to decide how to render *data*:
         *     - metrics → st.metric columns
         *     - strategy_card → bordered container with action / confidence / compound
         *     - table → st.dataframe
         *     - chart → st.plotly_chart (data contains figure JSON or base64 image)
         *     - text → st.markdown
         */
        ToolResultData: {
            /**
             * Tool Name
             * @description Which tool produced this result.
             */
            tool_name: string;
            /** @description Rendering hint for the frontend. */
            display_type: components["schemas"]["DisplayType"];
            /**
             * Data
             * @description Agent output payload.
             */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Summary
             * @description Natural-language summary produced by LM Studio.
             * @default
             */
            summary: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_telemetry_data_api_v1_telemetry_data_get: {
        parameters: {
            query: {
                year: number;
                gp: string;
                session: string;
                drivers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prewarm_api_v1_telemetry_prewarm_post: {
        parameters: {
            query: {
                year: number;
                gp: string;
                session: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gps_api_v1_telemetry_gps_get: {
        parameters: {
            query: {
                /** @description Year of the season (e.g., 2024) */
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sessions_api_v1_telemetry_sessions_get: {
        parameters: {
            query: {
                /** @description Year of the season */
                year: number;
                /** @description Grand Prix name */
                gp: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drivers_api_v1_telemetry_drivers_get: {
        parameters: {
            query: {
                /** @description Year of the season */
                year: number;
                /** @description Grand Prix name */
                gp: string;
                /** @description Session type (FP1, FP2, FP3, SQ, Q, S, R) */
                session: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lap_times: {
        parameters: {
            query: {
                /** @description Season year (2023, 2024 or 2025). */
                year: number;
                /** @description Grand Prix name (city/circuit form preferred, country names also accepted). */
                gp: string;
                /** @description Session code: R (race), Q (qualifying), S (sprint), SQ (sprint qualifying), FP1 / FP2 / FP3.  Default to R unless the user explicitly mentions another session. */
                session: string;
                /** @description Comma-separated 3-letter driver codes, e.g. 'VER,HAM,LEC'.  Pass a single code for a single-driver trace. */
                drivers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telemetry: {
        parameters: {
            query: {
                /** @description Season year (2023, 2024 or 2025). */
                year: number;
                /** @description Grand Prix name (city/circuit form preferred). */
                gp: string;
                /** @description Session code: R, Q, S, SQ, FP1, FP2, FP3.  Default R for race telemetry. */
                session: string;
                /** @description Driver — 3-letter code (VER, HAM, LEC, NOR, PIA, …). */
                driver: string;
                /** @description Lap number, integer between 2 and the race length.  Avoid lap 1 — usually no telemetry. */
                lap_number: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_data: {
        parameters: {
            query: {
                /** @description Season year (2023, 2024 or 2025). */
                year?: number;
                /** @description Grand Prix name (city/circuit form preferred, country names also accepted). */
                gp: string;
                /** @description Optional comma-separated 3-letter driver codes (e.g. 'VER,LEC').  Omit to get the whole field. */
                driver?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_circuit_domination_api_v1_circuit_domination_get: {
        parameters: {
            query: {
                /** @description Racing season year */
                year: number;
                /** @description Grand Prix name (e.g., 'Spain', 'Belgium') */
                gp: string;
                /** @description Session type */
                session: string;
                /** @description Comma-separated driver codes (e.g., 'VER,LEC,HAM') */
                drivers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_drivers: {
        parameters: {
            query: {
                /** @description Season year (2023, 2024 or 2025). */
                year: number;
                /** @description Grand Prix name (city/circuit form, e.g. 'Monaco', 'Monza', 'Spa-Francorchamps').  Country names like 'Italy' or 'Belgium' also accepted. */
                gp: string;
                /** @description Session code: FP1 / FP2 / FP3 (free practice), SQ (sprint qualifying), Q (qualifying), S (sprint race), R (race).  Use 'Q' for qualifying-lap comparisons, 'R' for race fastest-lap comparisons. */
                session: string;
                /** @description First driver — 3-letter code (VER, HAM, LEC, NOR, PIA, ALO, …). */
                driver1: string;
                /** @description Second driver — 3-letter code (VER, HAM, LEC, NOR, PIA, ALO, …). */
                driver2: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_chat_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_models_api_v1_chat_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    send_chat_message_api_v1_chat_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_message_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_status_api_v1_chat_status_get: {
        parameters: {
            query: {
                request_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_message_api_v1_chat_tool_message_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_message_stream_api_v1_chat_tool_message_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    available_gps_api_v1_strategy_available_gps_get: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    available_drivers_api_v1_strategy_available_drivers_get: {
        parameters: {
            query: {
                gp: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lap_range_api_v1_strategy_lap_range_get: {
        parameters: {
            query: {
                gp: string;
                driver: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lap_state_api_v1_strategy_lap_state_get: {
        parameters: {
            query: {
                gp: string;
                driver: string;
                lap: number;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_pace_api_v1_strategy_pace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_pace_range_api_v1_strategy_pace_range_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaceRangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_tire_range_api_v1_strategy_tire_range_post: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaceRangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_tire_api_v1_strategy_tire_post: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TireRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_situation_api_v1_strategy_situation_post: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SituationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_pit_api_v1_strategy_pit_post: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_radio_api_v1_strategy_radio_post: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RadioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_rag_api_v1_strategy_rag_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_strategy_api_v1_strategy_recommend_post: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radio_available_gps_api_v1_strategy_radio_available_gps_get: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radio_laps_api_v1_strategy_radio_laps_get: {
        parameters: {
            query: {
                gp: string;
                year?: number;
                driver?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radio_transcript_api_v1_strategy_radio_transcript_get: {
        parameters: {
            query: {
                gp: string;
                driver: string;
                lap: number;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_v1_strategy_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
